<html>
<head>
<title>郵便番号検索(静岡県版)</title>
<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js?ver=4.2.2'></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
</head>
<body>
<div id="form" style="text-align : center;">
<form action="query3.php" method="post" name="name">
<br/><br/><br/><br/><br/><br/><h2 style="font-family: cursive;">Welcome</h2><br />
<input type="text" id="Addr" name="Addr" class="Addr" placeholder="zip code or address"/><br/><br/>
<input type="submit" class="css_btn_class" value="load" name="button"/>
</form>
</div>
</body>
</html>

<?php
   $server = "localhost";
    $dbname = "CSexp1_cs13079DB";
    $user = "CSexp1_cs13079";
    $pass = "passwordA4";
    $tablename = "cs13079_part2";


    if (!$link = mysql_connect($server, $user, $pass)) {
        echo 'Could not connect to mysql';
        exit;
    }
    if (!mysql_select_db($dbname, $link)) {
        echo 'Could not select database';
        exit;
    }

        mysql_set_charset('utf8', $link);
        $sql =  "SELECT addr2,addr3 from  " . "$tablename" . "";
        if (!$result = mysql_query($sql)) {
            echo "DB Error, could not query the database\n";
            echo 'MySQL Error: ' . mysql_error();
            exit;
        }
        
        $MySQLlist = array();
        while($row = mysql_fetch_assoc($result)){
            array_push($MySQLlist, $row["addr2"].$row["addr3"]);
        }

        mysql_free_result($result);
        mysql_close($link);
    
?>

<script type="text/javascript">
$(function() {
  var MySQLlist = <?php echo json_encode($MySQLlist, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?>

    $("#Addr").autocomplete({
        source: MySQLlist,
        minLength: 2,
    });
});
</script>
<style type="text/css">
.css_btn_class {
    font-size:13px;
    font-family:Arial;
    font-weight:normal;
    -moz-border-radius:42px;
    -webkit-border-radius:42px;
    border-radius:42px;
    border:3px solid #83c41a;
    padding:24px 18px;
    text-decoration:none;
    background:-moz-linear-gradient( center top, #b8e356 39%, #a5cc52 66% );
    background:-ms-linear-gradient( top, #b8e356 39%, #a5cc52 66% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#b8e356', endColorstr='#a5cc52');
    background:-webkit-gradient( linear, left top, left bottom, color-stop(39%, #b8e356), color-stop(66%, #a5cc52) );
    background-color:#b8e356;
    color:#ffffff;
    display:inline-block;
    text-shadow:1px 3px 0px #86ae47;
    -webkit-box-shadow:inset 1px 0px 0px -1px #d9fbbe;
    -moz-box-shadow:inset 1px 0px 0px -1px #d9fbbe;
    box-shadow:inset 1px 0px 0px -1px #d9fbbe;
}.css_btn_class:hover {
    background:-moz-linear-gradient( center top, #a5cc52 39%, #b8e356 66% );
    background:-ms-linear-gradient( top, #a5cc52 39%, #b8e356 66% );
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#a5cc52', endColorstr='#b8e356');
    background:-webkit-gradient( linear, left top, left bottom, color-stop(39%, #a5cc52), color-stop(66%, #b8e356) );
    background-color:#a5cc52;
}.css_btn_class:active {
    position:relative;
    top:1px;
}
/* This css button was generated by css-button-generator.com */
#form {
              margin-left: auto;
              margin-right: auto;
}
html {
    background: url(green.jpg) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}
div {
    filter:alpha(opacity=100);
    -moz-opacity: 0.95;
    opacity: 0.95;
}
</style>

